<?php

return [
    'sections' => [
        [
            'letter' => 'A',
            'slug' => 'executive-summary',
            'title' => 'Executive Summary',
            'description' => 'Present the reporting period highlights, headline results, risks, and priority actions.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-a-executive-summary.png',
        ],
        [
            'letter' => 'B',
            'slug' => 'pdo-level-results-reporting',
            'title' => 'PDO Level Results Reporting',
            'description' => 'Report progress against programme development objective indicators and targets.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-b-pdo-results.png',
        ],
        [
            'letter' => 'C',
            'slug' => 'country-specific-targets',
            'title' => 'Country-Specific Targets',
            'description' => 'Capture national targets, current performance, and the evidence supporting each result.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-c-country-targets.png',
        ],
        [
            'letter' => 'D',
            'slug' => 'resilient-agricultural-production-capacity',
            'title' => 'Component 1 – (Re-)Building Resilient Agricultural Production Capacity',
            'description' => 'Track activities and results that strengthen resilient agricultural production capacity.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-d-resilient-production.png',
        ],
        [
            'letter' => 'E',
            'slug' => 'sustainable-natural-resource-management',
            'title' => 'Component 2 – Sustainable Natural Resource Management',
            'description' => 'Report sustainable land, water, ecosystem, and natural-resource management outcomes.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-e-natural-resources.png',
        ],
        [
            'letter' => 'F',
            'slug' => 'getting-to-market',
            'title' => 'Component 3 – Getting to Market',
            'description' => 'Record market access, value-chain, logistics, trade, and producer-linkage results.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-f-getting-to-market.png',
        ],
        [
            'letter' => 'G',
            'slug' => 'food-system-policy-regional-coordination',
            'title' => 'Component 4 – Food System Resilience Policy and Regional Coordination',
            'description' => 'Capture policy reforms, coordination milestones, and regional collaboration progress.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-g-policy-coordination.png',
        ],
        [
            'letter' => 'H',
            'slug' => 'beneficiary-reporting',
            'title' => 'Beneficiary Reporting',
            'description' => 'Report who the programme reached and how beneficiaries participated and benefited.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-h-beneficiary-reporting.png',
        ],
        [
            'letter' => 'I',
            'slug' => 'gender-and-social-inclusion',
            'title' => 'Gender and Social Inclusion',
            'description' => 'Track equitable participation, inclusion, accessibility, and gender-responsive results.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-i-gender-inclusion.png',
        ],
        [
            'letter' => 'J',
            'slug' => 'digital-agriculture-and-innovation',
            'title' => 'Digital Agriculture & Innovation',
            'description' => 'Document digital tools, data services, adoption, and agriculture innovation outcomes.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-j-digital-agriculture.png',
        ],
        [
            'letter' => 'K',
            'slug' => 'climate-change-and-resilience',
            'title' => 'Climate Change and Resilience',
            'description' => 'Report climate risks, adaptation measures, resilience gains, and response readiness.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-k-climate-resilience.png',
        ],
        [
            'letter' => 'L',
            'slug' => 'environmental-and-social-safeguards',
            'title' => 'Environmental and Social Safeguards',
            'description' => 'Track safeguard compliance, mitigation actions, incidents, and follow-up measures.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-l-safeguards.png',
        ],
        [
            'letter' => 'M',
            'slug' => 'financial-reporting',
            'title' => 'Financial Reporting',
            'description' => 'Submit financial performance, expenditure, disbursement, and variance information.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-m-financial-reporting.png',
        ],
        [
            'letter' => 'N',
            'slug' => 'procurement-reporting',
            'title' => 'Procurement Reporting',
            'description' => 'Report procurement plans, delivery status, contracts, and implementation constraints.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-n-procurement.png',
        ],
        [
            'letter' => 'O',
            'slug' => 'citizen-engagement-and-grm',
            'title' => 'Citizen Engagement and GRM',
            'description' => 'Capture engagement activities, feedback, grievances, resolution, and response times.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-o-citizen-engagement.png',
        ],
        [
            'letter' => 'P',
            'slug' => 'auc-regional-reporting-module',
            'title' => 'AUC Regional Reporting Module',
            'description' => 'Provide regional evidence and reporting inputs required for AUC coordination.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-p-auc-regional.png',
        ],
        [
            'letter' => 'Q',
            'slug' => 'lessons-success-stories-and-innovations',
            'title' => 'Lessons Learned, Success Stories, and Innovations',
            'description' => 'Share practical lessons, verified success stories, and innovations worth scaling.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-q-lessons-innovations.png',
        ],
        [
            'letter' => 'R',
            'slug' => 'au-mis-submission-checklist',
            'title' => 'AU MIS Submission Checklist',
            'description' => 'Review completeness, evidence, validation, and readiness before final submission.',
            'image' => 'admin/assets/images/member-state/reporting-sections/section-r-submission-checklist.png',
        ],
    ],
];
